language: node_js
node_js:
    - 0.10
    - 0.8

install:
  make dep

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install python-cheetah
    - npm install -g grunt-cli


script:
  grunt test